### ISSUE TITLE
Nothing is working

### ISSUE THREAD

**Issue by wahlforss** [oraclize/ethereum-examples#13]
When I use the oraclize API I get hundreds of errors. This is when I just copy paste your examples in remix...

One example is Potential Violation of Checks-Effects-Interaction pattern in usingOraclize.oraclize_query(uint256,string memory,string memory[] memory): Could potentially lead to re-entrancy vulnerability. <br/><i>Note:</i> Modifiers are currently not considered by this static analysis.

**Comment by bertani** [comment]
Mist has a well known long-standing bug where warnings are considered as errors, while prevents any code with warnings to compile.
This affects Mist only: browser-solidity (Remix), truffle, .. are not affected.
Unfortunately solidity 0.4.8 has introduced lot of warnings so code written for any version <0.4.8 now does not compile on Mist. In order to silence the warnings you can include "oraclizeAPI_0.5.sol", but at least one warning will be there anyway (removing it would introduce a breaking change).

This is a WONTFIX as the bug is in Mist.

If you need further assistance, you can also join our [gitter channel](https://gitter.im/oraclize/ethereum-api).
