### ISSUE TITLE
Example using random.org

### ISSUE THREAD

**Issue by madvas** [oraclize/ethereum-examples#2]
Could you please add example which uses https://www.random.org/ to get random numbers?

I've tried to make contract, but can't make it work somehow. I've tried that with [Ethereum Studio](https://live.ether.camp/) on sandboxed network, with Oraclize [plugin](http://blog.ether.camp/post/145202667083/ethereum-studio-integrates-oraclize).

This is what my contract looks like.

```
import "lib/std.sol";
import "lib/oraclizeAPI.sol";

contract Contract is named("Contract"), mortal, usingOraclize {

  uint256 public randomInt;
  event onCallback(string result);

  function Contract() {
    oraclize_setNetwork(networkID_consensys);
  }

  function __callback(bytes32 myid, string result) {
    onCallback(result);
    if (msg.sender != oraclize_cbAddress()) throw;
    randomInt = parseInt(result);
  }

  function update() {
    oraclize_query("URL", "json(https://api.random.org/json-rpc/1/invoke).result.random.data.0", '{"jsonrpc":"2.0","method":"generateIntegers","params":{"apiKey":"<ENTER API KEY HERE>","n":1,"min":1,"max":10,"replacement":true,"base":10},"id":458}');
  }
}
```

Don't forget to replace with your random.org apiKey. https://api.random.org/api-keys/beta

`__callback` is called, but string `result` is always empty.

Not sure if mistake is in my code or oraclize or Ethereum Studio Oraclize plugin.

Thank you

**Comment by nya1** [comment]
Hello @madvas,

thank you for getting in touch and my apologies for taking so long to answer, we didn't see this issue was opened - for any future issue please use our official dev support [gitter channel](https://gitter.im/oraclize/ethereum-api) or send us an email to info@oraclize.it :)

The ethereum-studio oraclize plugin had a small bug for some specific POST queries (while it's working fine on the live Ethereum mainnet/morden). Thank you for reporting this - the issue has just been addressed!

There is also a minor mistake in your code - at the beginning of the POST data in your oraclize_query you should specify a whitespace character or simply a `"\n"` (this is necessary to let Oraclize know that you want to send a JSON POST body request and not a POST url-encoded one).
The correct oraclize_query looks like this:

    oraclize_query("URL", "json(https://api.random.org/json-rpc/1/invoke).result.random.data.0", '\n{"jsonrpc":"2.0","method":"generateIntegers","params":{"apiKey":"<ENTER API KEY HERE>","n":1,"min":1,"max":10,"replacement":true,"base":10},"id":1}');
  
You should try the code again early next week as the fixed Oraclize plugin for Ethereum Studio will be updated in the IDE in a matter of days - we will send you an update here as soon as it's live.

Please feel free to come back to us with any further question you might have!

**Comment by nud3l** [comment]
Hi, it would be really helpful to have the hint with putting `"\n"`in front of the JSON string in the official getting started guide. Took me quite some time to figure out, why I wouldn't manage to get a valid JSON.

**Comment by hqthao** [comment]
I tried above string but always meet exception:

> Error: VM Exception while processing transaction: revert

You can test this here (I use an api test key)
       ```
 oraclize_query("URL",
            "json(https://api.random.org/json-rpc/1/invoke).result.random.data.0", '\n{"jsonrpc":"2.0","method":"generateIntegers","params":{"apiKey":"9844ab4d-52ef-4587-9cf3-20a6930a7f6e","n":1,"min":1,"max":10,"replacement":true,"base":10},"id":1}');

```

**Comment by D-Nice** [comment]
@hqthao Does your contract have a sufficient balance to pay for the query. Also which network are you trying this on?

**Comment by AndreMiras** [comment]
FWIW I've created draft notes about how to play with random.org through Oraclize https://github.com/AndreMiras/EtherollApp/blob/develop/docs/Oraclize.md
It was initially describing Etheroll a bit to the community, but it may be useful for other smart contract developers.
I definitely think Oraclize query tool should include ramdom.org example.
