### ISSUE TITLE
Random Numbers with Delimiter?

### ISSUE THREAD

**Issue by BrunoAl25** [oraclize/ethereum-examples#50]
It´s possible to receive the random numbers with a delimiter? eg: 12-67-89

I checked the docs https://docs.oraclize.it/#home and didn´t say anything about this

Thanks

**Comment by gskapka** [comment]
> [Is it] possible to receive the random numbers with a delimiter? eg: 12-67-89

Hi @BrunoAl25 - if you're talking about the Provable (Oraclize) random datasource, then no I'm afraid that's not possible since the random data received from that particular datasource are _bytes_, not integers. 

We designed it this way so that you the developer have maximum flexibility with what you may want to do with that randomness, and so you can convert the random bytes to whatever type(s)/format you may need.
