### ISSUE TITLE
How to speed up the service

### ISSUE THREAD

**Issue by ibragimHachaturyan** [oraclize/ethereum-examples#52]
Tell me a sore question, how to maximize the return of the value by the oracle as much as possible; we are developing a fair game on the blockchain and it is extremely important for us to make it quick, using the oracle we get a delay of at least a minute. Gas price 20gwei.

**Comment by gskapka** [comment]
Hello @ibragimHachaturyan - due to both the asynchronous nature of the blockchain plus the fact that you have to await not one but _two_ onchain transactions means that the Provable (Oraclize) service has an upper-bound in terms of response time and can only be as fast as the mining of those two transactions combined.

The portion of your query where the call is made to your API endpoint takes milliseconds, as does the orchestration behind the scenes of the `__callback` transaction. What takes the time is the _mining_ of the two transactions (yours to the Provable (Oraclize) service, and our response back to your contract). 

To get those mined as fast as possible you need to be using a high enough gas price to be in the `fast` category on the __[Eth Gas Station here](https://ethgasstation.info)__. Since you are already using `20gwei` your transactions are likely already being mined as quickly as possible, meaning there is very little room for a faster response to your queries because of the protocol itself.
